package com.example.weatheapp.utilities

enum class Constants {
    LANGUAGE,
    en,
    ar,
    LOCATION_METHOD,
    GPS,
    MAP,
    NOTIFICATION_STATUS,
    ENABLED,
    DISABLED,
    TempratureUnit,
    imperial,
    metric,
    standard,
    WindUnit,
    metr,
    mile,
    MAP_DESTINATION,
    FAVOURITE,
    HOME,
    FAVOURITE_LOCATION_LAT,
    FAVOURITE_LOCATION_LNG,
    HOME_DESTINATION,
    FAVDETAIE_DETAILS,
    ALARM,
    NOTIFICATION,
    ALARM_REQUEST_DELAY,
    ALARM_REQUEST_START,
    ALARM_REQUEST_END,
    NOTIFICATION_TYPE,
    ALERT_JSON_STRING

}